create table if not exists clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf_cnpj text,
  telefone text,
  email text,
  endereco text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists veiculos (
  id bigint generated by default as identity primary key,
  nome text not null,
  placa text,
  modelo text,
  capacidade integer,
  ano integer,
  status text not null default 'ativo',
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists modelos_contrato (
  id bigint generated by default as identity primary key,
  nome text not null,
  conteudo text not null,
  ativo boolean not null default true,
  versao integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists agendamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete restrict,
  veiculo_id bigint not null references veiculos(id) on delete restrict,
  data_saida date not null,
  hora_saida time not null,
  local_saida text not null,
  destino text not null,
  data_retorno date,
  hora_retorno time,
  local_retorno text,
  quantidade_passageiros integer not null,
  valor numeric(12,2) not null default 0,
  forma_pagamento text,
  observacoes text,
  status text not null default 'reservado',
  created_at timestamptz not null default now()
);

create table if not exists contratos (
  id bigint generated by default as identity primary key,
  numero_contrato text not null unique,
  agendamento_id bigint not null references agendamentos(id) on delete cascade,
  modelo_id bigint references modelos_contrato(id) on delete set null,
  conteudo_final text not null,
  status_assinatura text not null default 'pendente',
  created_at timestamptz not null default now()
);

insert into modelos_contrato (nome, conteudo, ativo, versao)
values (
  'Contrato padrão',
  'CONTRATO DE PRESTAÇÃO DE SERVIÇOS DE TRANSPORTE\n\nCONTRATO Nº: {{numero_contrato}}\n\nPelo presente instrumento particular, de um lado, {{empresa_nome}}, inscrita no CPF/CNPJ sob o nº {{empresa_documento}}, com endereço em {{empresa_endereco}}, telefone {{empresa_telefone}}, doravante denominada CONTRATADA, e, de outro lado, {{cliente_nome}}, inscrito(a) no CPF/CNPJ sob o nº {{cliente_documento}}, com endereço em {{cliente_endereco}}, telefone {{cliente_telefone}}, doravante denominado(a) CONTRATANTE, têm entre si justo e contratado o seguinte:\n\nCLÁUSULA 1ª – DO OBJETO\nO presente contrato tem por objeto a prestação de serviço de transporte para o seguinte itinerário:\n\nLocal de saída: {{local_saida}}\nData de saída: {{data_saida}}\nHora de saída: {{hora_saida}}\n\nDestino: {{destino}}\n\nLocal de retorno: {{local_retorno}}\nData de retorno: {{data_retorno}}\nHora de retorno: {{hora_retorno}}\n\nQuantidade de passageiros: {{quantidade_passageiros}}\n\nVeículo designado: {{veiculo_nome}}\nPlaca do veículo: {{veiculo_placa}}\nCapacidade do veículo: {{veiculo_capacidade}} passageiros\n\nCLÁUSULA 2ª – DO VALOR E FORMA DE PAGAMENTO\nPela prestação do serviço, o(a) CONTRATANTE pagará à CONTRATADA o valor total de R$ {{valor_total}}, por meio da seguinte forma de pagamento: {{forma_pagamento}}.\n\nCLÁUSULA 3ª – DAS OBSERVAÇÕES\n{{observacoes}}\n\nForo: {{foro_cidade}}\n\n{{cidade_assinatura}}, {{data_emissao}}.\n\n________________________________________\n{{empresa_nome}}\n\n________________________________________\n{{cliente_nome}}',
  true,
  1
)
on conflict do nothing;
